name: Continuous Integration
on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
jobs:
  verification:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v6
      - name: Sanity check
        run: pwd
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Running linter and code formatter
        run: npm run lint
      - name: Check
        run: npm run check
  test-fast:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run unit tests
        run: npx vitest run --reporter=default --run
  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Generate .env.test file
        run: |
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env.test
          echo "HOST_PORT=${{ vars.HOST_PORT }}" >> .env.test
          echo "APP_ENV=${{ vars.APP_ENV }}" >> .env.test
      - name: Build Docker image
        run: docker build -t nemless/nyx:${{ github.sha }} .
      - name: Start app
        run: docker compose -f docker-compose.test.yml --env-file .env.test up -d
      # - name: Setup test database
      #   run: npm run db:migrate:test
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e:ci
      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.test.yml --env-file .env.test down
      - name: Docker Login
        uses: docker/login-action@v4.2.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image onto Docker Hub
        run: docker push nemless/nyx:${{ github.sha }}
