name: Continuous Integration

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  verification:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v6
        with:
          node-version: 22

      - name: Sanity check
        run: pwd

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Running linter and code formatter
        run: npm run lint

      - name: Check
        run: npm run check

  test-fast:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run unit tests
        run: npx vitest run --reporter=default --run

  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate .env.test file
        run: |
          pwd
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env.test
          echo "ORIGIN=${{ vars.ORIGIN }}" >> .env.test
          echo "APP_ENV=${{ vars.APP_ENV }}" >> .env.test
          ls -l .env.test

      - name: Build app
        run: |
          npm run build:test
          ls

      - name: Setup test database
        run: |
          pwd
          npm run db:migrate:test

      - uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Generate .env.test
        run: |
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env.test
          echo "ORIGIN=${{ vars.ORIGIN }}" >> .env.test
          echo "APP_ENV=${{ vars.APP_ENV }}" >> .env.test
          pwd
          ls

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright
        run: npx playwright test
